<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USER-20170725RR" name="Test" tests="111" failures="29" timestamp="1 Feb 2018 10:42:48 GMT" time="591.09" errors="0">
  <testcase name="testcase" time="2.32" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.52" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.051" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.28" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="4.05" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.465" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="10.291" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.067" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="4.87" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="3.925" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.329" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="13.622" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.0" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.547" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.209" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.137" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="3.723" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.192" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="10.755" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="4.632" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="8.903" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.994" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.308" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.966" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="7.992" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="8.147" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.654" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="7.961" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="9.801" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.234" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.494" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.22" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.427" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="9.002" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.4" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.472" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="9.259" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.054" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.298" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="9.026" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.528" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.3" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.689" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.132" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.907" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.669" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.684" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.271" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.999" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="8.769" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.385" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.169" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.639" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.921" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="4.529" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="3.882" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.215" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="4.147" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.905" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.611" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.341" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.428" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="3.574" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.206" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="3.541" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="8.776" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.69" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.448" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.463" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.071" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.996" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.226" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="1.818" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="14.233" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.434" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.406" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="2.058" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.306" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.83" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="3.054" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="4.845" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.697" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.602" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.566" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.836" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.742" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.759" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.318" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="11.531" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="5.631" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.576" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.621" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.586" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.634" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.595" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.639" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.543" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.877" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.486" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.698" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.571" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.637" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="5.486" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="12.375" classname="com.Case.NewTest"/>
  <testcase name="testcase" time="6.406" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.901" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="8.636" classname="com.Case.NewTest">
    <failure type="org.openqa.selenium.WebDriverException" message="org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: &amp;apos;3.4.0&amp;apos;, revision: &amp;apos;unknown&amp;apos;, time: &amp;apos;unknown&amp;apos;
System info: host: &amp;apos;USER-20170725RR&amp;apos;, ip: &amp;apos;192.168.5.96&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_131&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'USER-20170725RR', ip: '192.168.5.96', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:336)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:323)
	at io.appium.java_client.AppiumDriver.doSwipe(AppiumDriver.java:383)
	at io.appium.java_client.android.AndroidDriver.swipe(AndroidDriver.java:186)
	at com.test.Base.dealData(Base.java:468)
	at com.Case.NewTest.testcase(NewTest.java:15)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
	... 36 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 49 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="14.078" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="14.087" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.002" classname="com.Case.NewTest">
    <failure type="org.openqa.selenium.WebDriverException" message="org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: &amp;apos;3.4.0&amp;apos;, revision: &amp;apos;unknown&amp;apos;, time: &amp;apos;unknown&amp;apos;
System info: host: &amp;apos;USER-20170725RR&amp;apos;, ip: &amp;apos;192.168.5.96&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_131&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'USER-20170725RR', ip: '192.168.5.96', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:235)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:533)
	at com.test.Base.dealData(Base.java:436)
	at com.Case.NewTest.testcase(NewTest.java:15)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
	... 32 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 45 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.0" classname="com.Case.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcase -->
</testsuite> <!-- Test -->
